In [2]:
import numpy as np

In [3]:
#Creating python list
list1=[1,2,3]

In [8]:
print(list1)
type(list1)

[1, 2, 3]


list

In [5]:
#Casting (Converting it to a numpy array or ndarray)
#np.array is the function to create arrays using numpy
array1=np.array(list1)

In [10]:
#one-dimension array, like vector
print(array1)
type(array1)

[1 2 3]


numpy.ndarray

In [9]:
#dtype function is used to know the data type of array
array1.dtype

dtype('int64')

In [11]:
list2=[[1,2,3],[4,5,6],[7,8,9]]

In [12]:
list2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
array2=np.array(list2)

In [14]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
#you can directly create numpy arrays using np.array functions
array3=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
array4=np.ones(20)

In [20]:
array4

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [33]:
array5=np.zeros(5)

In [34]:
#If you use quotes, it becomes a string and not a variable
print("array5")
type("array5")

array5


str

In [30]:
array5

array([0., 0., 0., 0., 0.])

In [27]:
#the 2 represents rows and the 3 represents columns
array6=np.zeros([2,3])

In [28]:
array6

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
type(array6)

numpy.ndarray

In [36]:
#nan stands for not defined as number
#it is equivalent to NAs in R
#it is used by pandas to handle missing values in ML models
array7=([np.nan,1,2])

In [37]:
array7

[nan, 1, 2]

In [39]:
#10=row
#5=column
#3=slab
array8=np.random.randn(10,5,3)

In [40]:
array8

array([[[-0.65121414, -0.39956681,  1.60953897],
        [-0.1464165 ,  2.84546963, -2.89469282],
        [-2.31093469,  0.23839536, -0.59536647],
        [-0.01540584,  1.98748555,  0.03534688],
        [ 0.29146534,  0.16839921, -0.09758998]],

       [[-1.86919943,  0.63265938,  0.28099546],
        [-0.65243496,  0.01543316,  0.137276  ],
        [ 0.04814389, -0.21203578, -1.31041396],
        [ 0.23861468,  0.76696165, -1.84633065],
        [-0.58975037, -0.15585876, -0.70683978]],

       [[-0.5649064 , -0.24923176,  0.2310744 ],
        [-0.15496257, -1.35249484, -0.23705299],
        [ 0.7544031 ,  1.14908175, -0.14549575],
        [-0.50538635,  0.04114752,  0.98180282],
        [-1.99027478, -1.13520226,  1.9905101 ]],

       [[ 0.31400445,  0.4843096 , -0.64745432],
        [-1.30684194,  0.07178724,  0.20022415],
        [-0.4496409 ,  0.09561646, -1.24295899],
        [ 0.39514166, -2.06998649, -0.28371498],
        [ 1.39961182, -0.12126607, -0.20496476]],

       [[-1.

In [43]:
array8b=np.random.randn(5,2)

In [44]:
array8b

array([[ 1.02113188,  1.52908733],
       [-1.35962312, -0.89123097],
       [ 0.7585198 , -1.02259562],
       [-2.10437352, -1.55752813],
       [-0.42735394,  0.33633118]])

In [45]:
array8c=np.random.randn(5,2,2)

In [46]:
array8c

array([[[ 0.66984916, -0.09201135],
        [-0.65144636, -1.20363305]],

       [[-0.26024996, -1.14281905],
        [ 0.24784507, -1.49816381]],

       [[-0.03292234,  0.19757901],
        [-1.01238222,  2.27631184]],

       [[ 0.62192943, -1.62552279],
        [ 0.15131716, -0.41539099]],

       [[ 0.06220505,  0.70898418],
        [-0.52825091,  1.40023714]]])

---

In [49]:
array9=array8[8]

In [50]:
array9

array([[-0.79969717,  1.71308038,  0.0471297 ],
       [ 0.40520012,  0.58588454, -0.89377406],
       [-0.1258571 ,  0.81694687, -0.34248311],
       [ 2.49659633, -0.43191102,  1.74690932],
       [-0.80545976, -1.7851537 , -0.67532412]])

In [63]:
array10=np.arange(25)

In [64]:
array10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
array11=array10.reshape(5,5)

In [59]:
array11

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
#Select specific row --> 2nd
array11[1]

array([5, 6, 7, 8, 9])

In [68]:
#Select specific cell
array11[1,1]

6

In [69]:
array11[0,1]

1

In [70]:
array11[0,4]

4

In [75]:
#[(a,b),(c,d)]
#Use a and c together to get first coordinate
#Use b and d together to get second coordinate
array11[(1,2),(3,4)]

array([ 8, 14])

In [77]:
print(array11)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [82]:
#Select all values for row or column
array11[:2,]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:
array11[:2,3:]

array([[3, 4],
       [8, 9]])

In [84]:
#Another way to selet values
array11[0][2]

2

In [85]:
array12=np.arange(10,36,2)

In [86]:
array12

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34])

In [87]:
array12[5]

20

In [88]:
array12[5:8]

array([20, 22, 24])

In [89]:
array12[5:]

array([20, 22, 24, 26, 28, 30, 32, 34])

In [90]:
array12[:5]

array([10, 12, 14, 16, 18])

In [91]:
array13=array12[0:12]

In [92]:
array13

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

In [93]:
#Creates a copy of array12
array12_copy=np.copy(array12)

In [96]:
print(array12_copy)
print(array12)

[10 12 14 16 18 20 22 24 26 28 30 32 34]
[10 12 14 16 18 20 22 24 26 28 30 32 34]
