In [1]:
l=[23245,27,546,215,-1234]

In [2]:
l

[23245, 27, 546, 215, -1234]

In [3]:
#Two types of arrays - built in and numpy arrays

In [5]:
import numpy as np

In [8]:
#np.array() function converts list to array
a=np.array(l)

In [9]:
a

array([23245,    27,   546,   215, -1234])

In [10]:
#can not have different data types in one array

In [11]:
b=np.array([12,455,63.3,True,"abc"])

In [12]:
b

array(['12', '455', '63.3', 'True', 'abc'], dtype='<U32')

In [13]:
print(b)

['12' '455' '63.3' 'True' 'abc']


In [14]:
#all have been converted to string

In [15]:
#less flexible than list

In [16]:
l.pop()

-1234

In [17]:
l


[23245, 27, 546, 215]

In [18]:
#pop() pops value out of list

In [19]:
a.mean()

4559.8

In [20]:
#many more functions within arrays vs. lists

In [23]:
c=np.array([12,455,63.3,True,False])

In [24]:
c

array([ 12. , 455. ,  63.3,   1. ,   0. ])

---

In [27]:
l

[23245, 27, 546, 215]

In [28]:
l[1:]

[27, 546, 215]

In [29]:
l[0:2]

[23245, 27]

In [30]:
l[::2]

[23245, 546]

In [31]:
#------------ Slicing Arrays

In [32]:
a

array([23245,    27,   546,   215, -1234])

In [33]:
a[2:]

array([  546,   215, -1234])

In [34]:
a[2:4]

array([546, 215])

In [38]:
a[4:2:-1]

array([-1234,   215])

In [39]:
b=a[2:4]

In [40]:
b

array([546, 215])

In [41]:
b[0]

546

In [42]:
b[:]

array([546, 215])

In [43]:
b[:]=111

In [44]:
b

array([111, 111])

In [45]:
a


array([23245,    27,   111,   111, -1234])

In [46]:
#when slicing --> we create a view and not a new array
#this is a way of saving space

In [47]:
c=a.copy()

In [48]:
#c is now a proper copy of a

In [49]:
c[0]=0

In [52]:
print(c)
print(a)

[    0    27   111   111 -1234]
[23245    27   111   111 -1234]


In [ ]:
#a will not be overwritten if you use the copy function
